[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = [
    "npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN",
    "pnpm install"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node dist/index.js"

