[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
    "echo '//registry.npmjs.org/:_authToken='$NPM_TOKEN > ~/.npmrc",
    "echo '@volley:registry=https://registry.npmjs.org/' >> ~/.npmrc",
    "echo 'always-auth=true' >> ~/.npmrc",
    "cat ~/.npmrc",
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/index.js"
