[build]
builder = "nixpacks"
buildCommand = "npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN && pnpm install && pnpm build"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/"
healthcheckTimeout = 30
